title: blog.rowanthorpe.com
description: My blog
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker
twitter:
  username: rowanthorpe
author: Rowan Thorpe
webmaster_verifications:
  google: tC02VvYYoVK7zHiqVlPg34J58LvGO3jD0OocWhfAEOI

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar
