title: blog.rowanthorpe.com
description: My blog
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-avatar

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
