title: blog.rowanthorpe.com
description: My blog
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker
twitter:
  username: rowanthorpe
author: rowanthorpe

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar
